### ISSUE TITLE
What's this plugin ?

### ISSUE THREAD

**Issue by diygun** [BoxOfDevs/SpeedSurvival#1]
Hi, wath this plugin do ?

**Comment by AvgZing** [comment]
speeds up survival

**Comment by HimbeersaftLP** [comment]
> speeds up survival

No sh*t Sherlock...

**Comment by diygun** [comment]
So the plugins is for e.g If i break log he give 2 or 3 log or if I break dimonds he give to me lots of or How the plugins work ?
